### ISSUE TITLE
panic: slice bounds out of range

### ISSUE THREAD

**Issue by issadarkthing** [melbahja/got#24]
Hi! I've tried to install `got` from the AUR and I received this error:
```sh
panic: runtime error: slice bounds out of range [:7] with length 4

goroutine 1 [running]:
main.main()
	/home/mohamed/work/dev/go/src/opensource/got/cmd/got/main.go:43 +0x583
```

**Comment by melbahja** [comment]
Did you have this error on the installation, or after running the `got` command ?
Can you show me the output of `go version` and  `got -v`

**Comment by issadarkthing** [comment]
I got the error when running `got help`.
The output of `go version`:
```sh
go version go1.15.2 linux/amd64
```
`got -v`:
```sh
flag provided but not defined: -v
Got - the fast http downloader.

Usage:
  got --out path/file.zip http://example.com/file.zip

Version:
  0.1.5+fd202da

Author:
  Mohamed Elbahja <bm9qdW5r@gmail.com>

Flags:
  -concurrency uint
    	Maximum chunks to download at the same time. (default 10)
  -out string
    	Downloaded file destination.
  -size uint
    	Maximum chunk size in bytes.
```

**Comment by poldi1405** [comment]
This issue was caused by the protocol-parsing. It's fixed in the current version.

**Comment by issadarkthing** [comment]
I went to build using `go get github.com/melbahja/got/cmd/got` but the error is occuring. I had to clone the repo and build it myself. Now the error has been fixed.

**Comment by poldi1405** [comment]
This may have been because to rebuild a binary that already was compiled you need to pass `-u` to `go get` this also updates the dependencies.
