### ISSUE TITLE
Issue while retrieving filesize

### ISSUE THREAD

**Issue by mpldr** [melbahja/got#31]
Sometimes (not always, not safely reproducible) I get unrealistic filesizes (see screenshot)

![20201202_10h56m36s_grim](https://user-images.githubusercontent.com/33086936/100857808-6be2f080-348d-11eb-8f79-34fc14c1bd9c.png)

This happens from time to time on URLs where it works on other times (this one was with a github repo download about 10 MiB in size)

**Comment by melbahja** [comment]
Is this happens only on some servers or random?

**Comment by poldi1405** [comment]
I have only witnessed it when downloading GitHub releases, but that's my main use so that probably doesn't say much.

**Comment by melbahja** [comment]
can you check with v0.6.0?

**Comment by mpldr** [comment]
Will do later today

**Comment by mpldr** [comment]
Seems to work, or has at least not happened yet.
